[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "QR-generator"
version = "0.1.2"
description = "A QR code generator built from scratch in Python."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }

authors = [
    { name = "Elijah Calderón" }
]

[project.optional-dependencies]
dev = [
    "pytest>=9"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
